// AppDelegate.swift
// Amtrak Companion — iOS App Delegate
//
// After `npx cap add ios`, Capacitor generates ios/App/App/AppDelegate.swift.
// Replace / augment that generated file with this content.
//
// Key responsibilities:
//   1. Activate AVAudioSession early (before the WKWebView loads) so background
//      audio is ready the instant the user presses Play.
//   2. (Phase 2) Check for a previously downloaded OTA web bundle and activate it.
//
// DEVICE BUILD: This file goes in ios/App/App/AppDelegate.swift (generated by cap add ios).
// WRITTEN, NOT COMPILED HERE. User must build on Mac with Xcode 15+.

import UIKit
import Capacitor
import AVFoundation

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
    ) -> Bool {

        // ── 1. AVAudioSession early activation ────────────────────────────────
        // Activate with .playback + .duckOthers as the default mode.
        // AudioSessionPlugin.load() will re-apply this; the early call here ensures
        // the category is set before ANY audio path runs (including WKWebView media).
        do {
            let session = AVAudioSession.sharedInstance()
            try session.setCategory(.playback,
                                    options: [.duckOthers, .interruptSpokenAudioAndMixWithOthers])
            try session.setActive(true)
        } catch {
            print("[AppDelegate] AVAudioSession activation failed: \(error.localizedDescription)")
            // Non-fatal — AudioSessionPlugin.load() will retry when the first play() is called.
        }

        // ── 2. OTA bundle check (Phase 2 placeholder) ─────────────────────────
        // If a previously downloaded OTA web bundle exists in applicationSupportDirectory,
        // redirect Capacitor's web server to serve it instead of the bundled assets.
        // This allows web-layer updates without TestFlight releases.
        let appSupport = FileManager.default.urls(
            for: .applicationSupportDirectory,
            in: .userDomainMask
        ).first!
        let otaWebDir = appSupport.appendingPathComponent("ota-web-bundle", isDirectory: true)
        let otaIndex = otaWebDir.appendingPathComponent("index.html")
        if FileManager.default.fileExists(atPath: otaIndex.path),
           let bridge = window?.rootViewController as? CAPBridgeViewController {
            bridge.setServerBasePath(otaWebDir.path)
        }

        return true
    }

    // ── Standard Capacitor delegation ─────────────────────────────────────────

    func applicationWillResignActive(_ application: UIApplication) {}
    func applicationDidEnterBackground(_ application: UIApplication) {}
    func applicationWillEnterForeground(_ application: UIApplication) {}
    func applicationDidBecomeActive(_ application: UIApplication) {}

    func application(
        _ app: UIApplication,
        open url: URL,
        options: [UIApplication.OpenURLOptionsKey: Any] = [:]
    ) -> Bool {
        return ApplicationDelegateProxy.shared.application(app, open: url, options: options)
    }

    func application(
        _ application: UIApplication,
        continue userActivity: NSUserActivity,
        restorationHandler: @escaping ([UIUserActivityRestoring]?) -> Void
    ) -> Bool {
        return ApplicationDelegateProxy.shared.application(
            application,
            continue: userActivity,
            restorationHandler: restorationHandler
        )
    }
}
