#!/usr/bin/env python3
"""
Compare ASP programs generated by orchestrator vs direct call to find differences.
"""

import json
import sys
from pathlib import Path
from datetime import datetime

project_root = Path(__file__).parent.parent.parent.parent
env_path = project_root / '.env'
if env_path.exists():
    from dotenv import load_dotenv
    load_dotenv(env_path)

sys.path.insert(0, str(project_root))
sys.path.insert(0, str(project_root / "letta"))

from scheduling_orchestrator.orchestrate_scheduling import orchestrate_scheduling
from scheduling_orchestrator.dspy_extraction import extract_with_fallback
from scheduling_orchestrator.normalizer import normalize_events
from scheduling_orchestrator.horizon_reducer import reduce_horizon_to_feasible_window
from scheduling_orchestrator.fact_generator import generate_asp_program
from scheduling_orchestrator.clingo_wrapper import ClingoSolver

def load_events_from_example(example_file: Path) -> dict:
    """Load events from example_event_data.md"""
    events_by_participant = {}
    
    with open(example_file, 'r') as f:
        content = f.read()
    
    participants = [
        "cdorsey@concord.org",
        "sbrau@concord.org",
        "dkehoe@concord.org"
    ]
    
    for participant in participants:
        marker = f"Event data for {participant}:"
        idx = content.find(marker)
        if idx == -1:
            continue
        
        json_start = content.find('[', idx)
        bracket_count = 0
        json_end = json_start
        for i, char in enumerate(content[json_start:], json_start):
            if char == '[':
                bracket_count += 1
            elif char == ']':
                bracket_count -= 1
                if bracket_count == 0:
                    json_end = i + 1
                    break
        
        json_str = content[json_start:json_end]
        try:
            events = json.loads(json_str)
            normalized_events = []
            for event in events:
                start_val = event.get("start", "")
                if isinstance(start_val, dict):
                    start_str = start_val.get("dateTime", "")
                else:
                    start_str = str(start_val) if start_val else ""
                
                end_val = event.get("end", "")
                if isinstance(end_val, dict):
                    end_str = end_val.get("dateTime", "")
                else:
                    end_str = str(end_val) if end_val else ""
                
                normalized = {
                    "id": event.get("id", ""),
                    "title": event.get("summary") or event.get("title", ""),
                    "start": start_str,
                    "end": end_str,
                    "locked": event.get("locked", False),
                    "protected": event.get("protected", False),
                    "flexible": event.get("flexible", True),
                    "internal_only": event.get("internal_only", True),
                    "number_of_attendees": event.get("number_of_attendees", 0)
                }
                normalized_events.append(normalized)
            
            events_by_participant[participant] = normalized_events
        except json.JSONDecodeError:
            continue
    
    return events_by_participant


if __name__ == "__main__":
    print("="*80)
    print("COMPARE ASP PROGRAMS")
    print("="*80)
    
    example_file = Path(__file__).parent / "example_event_data.md"
    events_by_participant = load_events_from_example(example_file)
    
    context_json = {
        "timeframe": {
            "from": "2025-12-03",
            "to": "2025-12-12",
            "tz": "America/New_York"
        },
        "participants": [
            {"id": "cdorsey@concord.org", "email": "cdorsey@concord.org", "work_hours": "M-F 09:00-17:00"},
            {"id": "sbrau@concord.org", "email": "sbrau@concord.org", "work_hours": "M-F 09:00-17:00"},
            {"id": "dkehoe@concord.org", "email": "dkehoe@concord.org", "work_hours": "M-F 09:00-17:00"}
        ],
        "policy": {
            "hard": {"min_gap_min": 0},
            "soft": {}
        },
        "slot_size_minutes": 15
    }
    
    utterance = "Find me possible 45-minute meeting slots with Sue and Danielle between Dec. 3 and 12."
    
    print("\n1. Getting scheduling problem (as orchestrator does)...")
    scheduling_problem = extract_with_fallback(utterance, context_json)
    
    print("\n2. Normalizing events (as orchestrator does)...")
    normalized_data = normalize_events(events_by_participant, context_json=context_json)
    
    print(f"   Original slots: {normalized_data['slot_indexer'].total_slots}")
    
    print("\n3. Reducing horizon (as orchestrator does)...")
    asp_normalized_data = reduce_horizon_to_feasible_window(
        normalized_data,
        scheduling_problem,
        max_slots=48,
        prefer_time_window=True
    )
    
    print(f"   Reduced slots: {asp_normalized_data['slot_indexer'].total_slots}")
    print(f"   Reduced horizon: {asp_normalized_data['slot_indexer'].horizon_start} to {asp_normalized_data['slot_indexer'].horizon_end}")
    
    print("\n4. Generating ASP program (as orchestrator does)...")
    asp_program_orchestrator = generate_asp_program(
        asp_normalized_data,
        scheduling_problem,
        request_id="q1",
        include_soft_constraints=True,
        include_work_hours=True,
        include_min_gap=True,
        include_locked_events=True,
        phase=4,
        allow_multi_move=True
    )
    
    print(f"   Program size: {len(asp_program_orchestrator)} chars, {len(asp_program_orchestrator.splitlines())} lines")
    
    # Save orchestrator's program
    with open(Path(__file__).parent / "asp_program_orchestrator.lp", 'w') as f:
        f.write(asp_program_orchestrator)
    print("   Saved to: asp_program_orchestrator.lp")
    
    print("\n5. Testing orchestrator's program with Clingo...")
    solver = ClingoSolver(timeout=30)
    model1, stats1, result1 = solver.solve(asp_program_orchestrator)
    
    print(f"   Models found: {stats1.get('models_found', 0)}")
    print(f"   Satisfiable: {stats1.get('satisfiable', 'N/A')}")
    print(f"   Solve time: {stats1.get('solve_time_ms', 0)} ms")
    print(f"   Ground time: {stats1.get('ground_time_ms', 0)} ms")
    if stats1.get('error'):
        print(f"   Error: {stats1['error']}")
    
    print("\n6. Comparing with direct test program...")
    # Check what direct test uses (from debug_orchestrator_asp.py)
    # The direct test should be identical, but let's verify
    
    # Key facts comparison
    facts1 = asp_program_orchestrator.split('\n')
    window_facts1 = [f for f in facts1 if f.strip().startswith('window(q1,')]
    occurs_facts1 = [f for f in facts1 if f.strip().startswith('occurs_if_start(q1,')]
    busy_facts1 = [f for f in facts1 if 'busy(' in f and 'cdorsey@concord.org' in f]
    
    print(f"   window facts: {len(window_facts1)}")
    print(f"   occurs_if_start facts: {len(occurs_facts1)}")
    print(f"   busy facts (cdorsey): {len(busy_facts1)}")
    
    # Check if program has correct encoding
    has_multi_move = 'Multi-Move Variant' in asp_program_orchestrator
    has_enhanced_soft = 'Enhanced Soft Constraints' in asp_program_orchestrator
    min_gap_locked = any('locked_event(P, T2)' in f and 'min_gap' in f for f in facts1)
    min_gap_busy = any('busy(P, T2)' in f and 'min_gap' in f and 'locked_event' not in f for f in facts1)
    
    print(f"\n7. Program encoding check:")
    print(f"   Has Multi-Move Variant: {has_multi_move}")
    print(f"   Has Enhanced Soft Constraints: {has_enhanced_soft}")
    print(f"   min_gap uses locked_event: {min_gap_locked}")
    print(f"   min_gap uses busy (wrong): {min_gap_busy}")
    
    if stats1.get('models_found', 0) == 0 and stats1.get('satisfiable') == False:
        print("\n8. Investigating why UNSAT...")
        # Check if there are any window facts
        if len(window_facts1) == 0:
            print("   ⚠️  NO WINDOW FACTS - this would make it UNSAT!")
        else:
            print(f"   ✓ Window facts exist: {len(window_facts1)}")
            print(f"   First few window facts:")
            for f in window_facts1[:5]:
                print(f"     {f.strip()}")

