"""
Staff data for identity migration.

This file contains all Concord staff data extracted from the provided listing.
Used by migrate_staff_properties.py to populate identity properties and tags.
"""

# Map email to staff data
# Keys match identifier_key in Letta identities
STAFF_DATA = {
    "lbondaryk@concord.org": {
        "title": "Chief Technology Officer",
        "home_state": "MA",
        "home_city": None,
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["administrator", "co-pi"],
        "departments": ["administration", "software-development"],
        "projects": [
            {"name": "Overhead", "role": None},
            {"name": "MODS", "role": None},
            {"name": "DataGOAT", "role": None},
            {"name": "ISLAND", "role": None},
            {"name": "Brainwaves", "role": None},
        ],
    },
    "sbrau@concord.org": {
        "title": "Director of Finance",
        "home_state": "MA",
        "home_city": None,
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["administrator"],
        "departments": ["f-and-a", "administration"],
        "projects": [],
    },
    "kbrown@concord.org": {
        "title": "Tech Program Manager",
        "home_state": "MA",
        "home_city": None,
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["project-manager", "scrum-master"],
        "departments": ["software-development"],
        "projects": [
            {"name": "Overhead", "role": None},
            {"name": "Seismic", "role": None},
            {"name": "TechNexus", "role": None},
            {"name": "Tech Dev", "role": None},
        ],
    },
    "lbuoncuore@concord.org": {
        "title": "Grants Manager",
        "home_state": "MA",
        "home_city": None,
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["finance"],
        "departments": ["f-and-a"],
        "projects": [],
    },
    "jchao@concord.org": {
        "title": "Learning Scientist",
        "home_state": "MA",
        "home_city": None,
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["researcher", "pi", "co-pi"],
        "departments": ["program-staff"],
        "projects": [
            {"name": "M2Studio", "role": "pi"},
            {"name": "Logic DS", "role": "copi"},
            {"name": "StoryQ 2", "role": "pi"},
            {"name": "AI for VS", "role": "pi"},
            {"name": "Neural Net Makers", "role": "pi"},
        ],
    },
    "scytacki@concord.org": {
        "title": "Senior Software Architect",
        "home_state": "MA",
        "home_city": None,
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["software-developer", "software-architect"],
        "departments": ["software-development"],
        "projects": [],
    },
    "ddamelin@concord.org": {
        "title": "Senior Scientist",
        "home_state": "MA",
        "home_city": None,
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["pi", "co-pi"],
        "departments": ["program-staff"],
        "projects": [
            {"name": "FABLES", "role": "copi"},
            {"name": "CODAP V3", "role": None},
            {"name": "MultiData", "role": "copi"},
            {"name": "DST", "role": None},
            {"name": "CODAP POSE 1", "role": "pi"},
            {"name": "Data By Voice", "role": "pi"},
            {"name": "Valhalla DSR", "role": None},
            {"name": "Cisco", "role": "pi"},
            {"name": "Mapping Time", "role": None},
        ],
    },
    "cdorsey@concord.org": {
        "title": "President & CEO",
        "home_state": "MA",
        "home_city": None,
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["administrator", "pi", "co-pi"],
        "departments": ["administration"],
        "projects": [
            {"name": "Overhead", "role": None},
            {"name": "DST", "role": "pi"},
            {"name": "Inscriptions 2", "role": "copi"},
            {"name": "CODAP POSE 1", "role": "copi"},
            {"name": "Valhalla DSR", "role": "pi"},
            {"name": "Cisco", "role": None},
            {"name": "Mapping Time", "role": "pi"},
        ],
    },
    "rellis@concord.org": {
        "title": "Curriculum Developer",
        "home_state": "MI",
        "home_city": None,
        "us_region": "Midwest",
        "home_office": "Concord",
        "roles": ["curriculum-development", "project-management"],
        "departments": ["program-staff"],
        "projects": [
            {"name": "M2Studio", "role": None},
            {"name": "MODS", "role": None},
            {"name": "Logic DS", "role": None},
            {"name": "StoryQ 2", "role": None},
            {"name": "AI for VS", "role": None},
            {"name": "Neural Net Makers", "role": None},
            {"name": "ISLAND", "role": None},
        ],
    },
    "wfinzer@concord.org": {
        "title": "Senior Scientist",
        "home_state": "CA",
        "home_city": "Pacific Grove",
        "us_region": "West Coast",
        "home_office": "CA",
        "roles": ["software-developer", "co-pi"],
        "departments": ["program-staff"],
        "projects": [
            {"name": "CODAP V3", "role": "pi"},
            {"name": "MultiData", "role": None},
            {"name": "ESTEEM 2", "role": None},
            {"name": "DST", "role": "copi"},
            {"name": "CODAP POSE 1", "role": None},
            {"name": "Neural Net Makers", "role": None},
            {"name": "Data By Voice", "role": "copi"},
            {"name": "Cisco", "role": None},
        ],
    },
    "tfristoe@concord.org": {
        "title": "Senior Software Engineer",
        "home_state": "CA",
        "home_city": None,
        "us_region": "West Coast",
        "home_office": "CA",
        "roles": ["software-developer"],
        "departments": ["software-development"],
        "projects": [],
    },
    "kjesseneller@concord.org": {
        "title": "Research Scientist",
        "home_state": "RI",
        "home_city": None,
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["researcher", "pi"],
        "departments": ["program-staff"],
        "projects": [
            {"name": "DSAIY", "role": "pi"},
            {"name": "TOTAL", "role": None},
        ],
    },
    "dkehoe@concord.org": {
        "title": "Director of Development",
        "home_state": "MA",
        "home_city": None,
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["fundraiser", "administrator"],
        "departments": ["f-and-a", "administration"],
        "projects": [],
    },
    "hlee@concord.org": {
        "title": "Senior Research Scientist",
        "home_state": "CA",
        "home_city": "Santa Cruz",
        "us_region": "West Coast",
        "home_office": "CA",
        "roles": ["researcher", "pi"],
        "departments": ["program-staff"],
        "projects": [
            {"name": "Youthquake", "role": "copi"},
            {"name": "ISLAND", "role": "pi"},
            {"name": "APLUS", "role": "pi"},
        ],
    },
    "tlord@concord.org": {
        "title": "Senior Project Manager",
        "home_state": "MA",
        "home_city": "Natick",
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["project-manager"],
        "departments": ["program-staff"],
        "projects": [
            {"name": "Youthquake", "role": None},
            {"name": "AI for VS", "role": None},
            {"name": "Pele", "role": None},
            {"name": "ISLAND", "role": None},
            {"name": "APLUS", "role": None},
            {"name": "Seismic ML", "role": None},
        ],
    },
    "clore@concord.org": {
        "title": "Research Associate",
        "home_state": "NY",
        "home_city": "Cornell",
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["researcher", "pi"],
        "departments": ["program-staff"],
        "projects": [
            {"name": "DST", "role": None},
            {"name": "Youthquake", "role": None},
            {"name": "AI for VS", "role": None},
            {"name": "Pele", "role": None},
            {"name": "Mapping Time", "role": None},
            {"name": "ISLAND", "role": None},
            {"name": "APLUS", "role": None},
            {"name": "Seismic ML", "role": "pi"},
        ],
    },
    "dmartin@concord.org": {
        "title": "Principal Software Engineer",
        "home_state": "MA",
        "home_city": None,
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["software-developer"],
        "departments": ["software-development"],
        "projects": [],
    },
    "emcelroy@concord.org": {
        "title": "Software Engineer",
        "home_state": "NH",
        "home_city": None,
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["software-developer"],
        "departments": ["software-development"],
        "projects": [],
    },
    "cmcintyre@concord.org": {
        "title": "Communications Director",
        "home_state": "MA",
        "home_city": "Sterling",
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["communications", "administrator"],
        "departments": ["administration", "f-and-a"],
        "projects": [
            {"name": "Overhead", "role": None},
            {"name": "Inscriptions 2", "role": None},
            {"name": "Data By Voice", "role": None},
            {"name": "Valhalla DSR", "role": None},
            {"name": "Cisco", "role": None},
            {"name": "Mapping Time", "role": None},
        ],
    },
    "kmiller@concord.org": {
        "title": "Research Associate",
        "home_state": "MA",
        "home_city": "Amherst",
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["researcher", "co-pi"],
        "departments": ["program-staff"],
        "projects": [
            {"name": "DS4E", "role": None},
            {"name": "DST", "role": None},
            {"name": "LEADS", "role": "copi"},
            {"name": "Valhalla DSR", "role": None},
            {"name": "Mapping Time", "role": "copi"},
        ],
    },
    "apallant@concord.org": {
        "title": "Senior Research Scientist",
        "home_state": "MA",
        "home_city": "Framingham",
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["pi", "researcher"],
        "departments": ["program-staff"],
        "projects": [
            {"name": "Overhead", "role": None},
            {"name": "Youthquake", "role": "pi"},
            {"name": "Pele", "role": "copi"},
            {"name": "ISLAND", "role": "copi"},
            {"name": "APLUS", "role": "copi"},
            {"name": "Seismic ML", "role": "copi"},
        ],
    },
    "jraiff@concord.org": {
        "title": "Director of HR",
        "home_state": "MA",
        "home_city": "Concord",
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["hr"],
        "departments": ["f-and-a"],
        "projects": [],
    },
    "lstephens@concord.org": {
        "title": "Research Scientist",
        "home_state": "MA",
        "home_city": "Amherst",
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["researcher", "pi"],
        "departments": ["program-staff"],
        "projects": [
            {"name": "Overhead", "role": None},
            {"name": "MultiData", "role": "pi"},
            {"name": "MODS", "role": None},
            {"name": "Logic DS", "role": None},
            {"name": "Data By Voice", "role": None},
            {"name": "DSAIY", "role": None},
        ],
    },
    "kswenson@concord.org": {
        "title": "Principal Software Engineer",
        "home_state": "CA",
        "home_city": "Irvine",
        "us_region": "West Coast",
        "home_office": "CA",
        "roles": ["software-developer"],
        "departments": ["software-development"],
        "projects": [],
    },
    "mtirenin@concord.org": {
        "title": "UX/UI Designer",
        "home_state": "NJ",
        "home_city": None,
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["designer"],
        "departments": ["software-development"],
        "projects": [],
    },
    "awagh@concord.org": {
        "title": "Research Scientist",
        "home_state": "MA",
        "home_city": None,
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["pi", "researcher"],
        "departments": ["program-staff"],
        "projects": [
            {"name": "MoDa", "role": "pi"},
        ],
    },
    "nrivera@concord.org": {
        "title": "Finance Administrator",
        "home_state": "MA",
        "home_city": None,
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["finance", "support"],
        "departments": ["f-and-a"],
        "projects": [],
    },
    "phorwitz@concord.org": {
        "title": "Senior Scientist Emeritus",
        "home_state": "MA",
        "home_city": None,
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["pi"],
        "departments": ["program-staff"],
        "projects": [],
    },
    "sandbox@concord.org": {
        "title": "Demo Staff Member",
        "home_state": "MA",
        "home_city": None,
        "us_region": "East Coast",
        "home_office": "Concord",
        "roles": ["stand-in"],
        "departments": ["program-staff"],
        "projects": [],
    },
}

# All known projects (for reference/validation)
PROJECTS = {
    "110": "Overhead",
    "353": "M2Studio",
    "355": "FABLES",
    "364": "DS4E",
    "365": "CODAP V3",
    "368": "MultiData",
    "371": "MODS",
    "372": "Logic DS",
    "374": "Logic DS",
    "376": "ESTEEM 2",
    "378": "DST",
    "381": "Inscriptions 2",
    "384": "StoryQ 2",
    "386": "Youthquake",
    "387": "AI for VS",
    "388": "CODAP POSE 1",
    "389": "Neural Net Makers",
    "391": "Data By Voice",
    "392": "DataGOAT",
    "393": "Pele",
    "394": "DSAIY",
    "396": "LEADS",
    "397": "Valhalla DSR",
    "401": "MoDa",
    "403": "Cisco",
    "405": "Mapping Time",
    "406": "ISLAND",
    "407": "APLUS",
    "408": "Seismic",
    "409": "TechNexus",
    "411": "Brainwaves",
}

# Standard values for validation
VALID_US_REGIONS = ["East Coast", "West Coast", "Midwest"]
VALID_HOME_OFFICES = ["Concord", "CA"]
VALID_DEPARTMENTS = [
    "administration",
    "software-development",
    "program-staff",
    "f-and-a",
]
VALID_ROLES = [
    "administrator",
    "researcher",
    "software-developer",
    "software-architect",
    "project-manager",
    "scrum-master",
    "pi",
    "co-pi",
    "curriculum-development",
    "finance",
    "fundraiser",
    "communications",
    "hr",
    "designer",
    "support",
    "stand-in",
]
