#!/usr/bin/env python3
"""
Trigger Slack Analytics CSV exports using browser automation.

This script clicks the "Export CSV" button for analytics but doesn't wait for download.
The CSV files are generated by Slack and available in your Slack workspace's Files.

Usage:
    python3 slack_analytics_trigger_export.py --type channels
    python3 slack_analytics_trigger_export.py --type members
    python3 slack_analytics_trigger_export.py --type all
"""

import asyncio
import argparse
from pathlib import Path
from playwright.async_api import async_playwright
from datetime import datetime

SLACK_WORKSPACE_URL = "https://concord-consortium.slack.com"
ANALYTICS_PAGES = {
    "channels": f"{SLACK_WORKSPACE_URL}/admin/stats#channels",
    "members": f"{SLACK_WORKSPACE_URL}/admin/stats#members",
    "overview": f"{SLACK_WORKSPACE_URL}/admin/stats#overview",
}

async def trigger_export(
    analytics_type: str = "channels",
    headless: bool = True,
    screenshot_dir: str = "./slack_analytics_screenshots",
    auth_save_path: str = "./slack_auth_state.json"
):
    """
    Trigger Slack analytics CSV export by clicking the Export button.
    
    Args:
        analytics_type: Type of analytics (channels, members, overview)
        headless: Run browser in headless mode
        screenshot_dir: Directory to save screenshots
        auth_save_path: Path to save/load authentication state
    """
    
    # Ensure screenshot directory exists
    screenshot_path_dir = Path(screenshot_dir).resolve()
    screenshot_path_dir.mkdir(parents=True, exist_ok=True)
    
    auth_path = Path(auth_save_path)
    
    results = {
        "success": False,
        "analytics_type": analytics_type,
        "button_clicked": False,
        "errors": []
    }
    
    async with async_playwright() as p:
        # Launch browser
        browser = await p.chromium.launch(headless=headless)
        
        # Try to load existing auth state
        context_options = {}
        
        if auth_path.exists():
            print(f"✓ Loading saved authentication from {auth_path}")
            context_options["storage_state"] = str(auth_path)
        else:
            print("⚠ No saved authentication found. You'll need to log in.")
        
        context = await browser.new_context(**context_options)
        page = await context.new_page()
        
        # Navigate to analytics page
        target_url = ANALYTICS_PAGES.get(analytics_type)
        if not target_url:
            results["errors"].append(f"Unknown analytics type: {analytics_type}")
            await browser.close()
            return results
        
        print(f"→ Navigating to {target_url}")
        try:
            await page.goto(target_url, wait_until="domcontentloaded", timeout=15000)
            await page.wait_for_timeout(2000)
        except Exception as e:
            results["errors"].append(f"Navigation failed: {e}")
            await browser.close()
            return results
        
        # Check if we're at login page
        current_url = page.url
        if "/signin" in current_url or "workspace-signin" in current_url:
            print("\n⚠ Not logged in. Please log in to Slack...")
            print("   The browser will stay open for you to authenticate.")
            print("   After logging in, press Enter to continue.\n")
            
            # Wait for successful login
            try:
                await page.wait_for_url(
                    lambda url: "/signin" not in url and "workspace-signin" not in url,
                    timeout=120000
                )
                print("✓ Login successful!")
                
                # Save authentication state
                await context.storage_state(path=str(auth_path))
                print(f"✓ Authentication saved to {auth_path}")
                
                # Navigate to analytics page again
                await page.goto(target_url, wait_until="domcontentloaded")
                await page.wait_for_timeout(2000)
                
            except Exception as e:
                results["errors"].append(f"Login timeout or failed: {e}")
                await browser.close()
                return results
        else:
            print("✓ Already authenticated")
        
        # Wait for the analytics page to load
        print("→ Waiting for analytics page to load...")
        await page.wait_for_timeout(3000)
        
        # Click the appropriate analytics tab
        print(f"→ Clicking {analytics_type} tab...")
        try:
            tab_selector = f'a[data-analytics-tab="{analytics_type}"]'
            await page.click(tab_selector, timeout=5000)
            print(f"✓ Clicked {analytics_type} tab")
            
            # Wait for tab content to load
            await page.wait_for_timeout(5000)
        except Exception as e:
            print(f"⚠ Could not click tab: {e}")
        
        # Wait for data to render
        await page.wait_for_timeout(2000)
        
        # Dismiss any modals/coachmarks/tutorials that might be blocking
        print("→ Dismissing any tutorial modals...")
        try:
            # Try common modal close selectors
            close_selectors = [
                'button[aria-label="Close"]',
                'button[data-qa="coachmark_close"]',
                '.c-coachmark button:has-text("Got it")',
                '.c-coachmark button:has-text("OK")',
                '.c-coachmark button:has-text("Dismiss")',
                '.ReactModal__Overlay button[aria-label="Close"]',
            ]
            for close_sel in close_selectors:
                try:
                    close_btn = page.locator(close_sel).first
                    if await close_btn.count() > 0 and await close_btn.is_visible():
                        await close_btn.click(timeout=2000)
                        print(f"✓ Dismissed modal with: {close_sel}")
                        await page.wait_for_timeout(1000)
                        break
                except:
                    continue
            
            # Alternative: Press Escape key to close modals
            await page.keyboard.press('Escape')
            await page.wait_for_timeout(500)
            
        except Exception as e:
            print(f"  Note: {e}")
        
        # Take a screenshot before clicking
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        screenshot_before = screenshot_path_dir / f"slack_{analytics_type}_before_{timestamp}.png"
        await page.screenshot(path=str(screenshot_before))
        print(f"✓ Screenshot saved: {screenshot_before}")
        
        # Find and click the Export CSV button
        print("→ Looking for Export CSV button...")
        
        # Try multiple selectors for the button
        button_selectors = [
            f'button[data-qa="analytics_{analytics_type}_csv-header-action"]',
            'button[aria-label="Export CSV"]',
            'button:has-text("Export CSV")',
            'button.c-data_table_header_action:has-text("Export")',
        ]
        
        button_clicked = False
        for selector in button_selectors:
            try:
                button = page.locator(selector).first
                count = await button.count()
                if count > 0:
                    print(f"✓ Found button with selector: {selector}")
                    await button.click(timeout=5000)
                    print(f"✓ Clicked Export CSV button for {analytics_type}")
                    button_clicked = True
                    results["button_clicked"] = True
                    
                    # Wait a moment for any confirmation
                    await page.wait_for_timeout(2000)
                    
                    # Take screenshot after click
                    screenshot_after = screenshot_path_dir / f"slack_{analytics_type}_after_{timestamp}.png"
                    await page.screenshot(path=str(screenshot_after))
                    print(f"✓ Post-click screenshot: {screenshot_after}")
                    
                    results["success"] = True
                    break
                    
            except Exception as e:
                print(f"  × Selector failed: {selector} - {e}")
                continue
        
        if not button_clicked:
            results["errors"].append(
                f"Could not find or click Export CSV button for {analytics_type}"
            )
        
        # Save final state
        await context.storage_state(path=str(auth_path))
        await browser.close()
    
    return results


async def main():
    parser = argparse.ArgumentParser(
        description="Trigger Slack Analytics CSV exports"
    )
    parser.add_argument(
        "--type",
        choices=["channels", "members", "overview", "all"],
        default="channels",
        help="Type of analytics to export (use 'all' for all types)"
    )
    parser.add_argument(
        "--headless",
        action="store_true",
        help="Run browser in headless mode (no visible window)"
    )
    parser.add_argument(
        "--screenshot-dir",
        default="./slack_analytics_screenshots",
        help="Directory to save screenshots"
    )
    parser.add_argument(
        "--auth-file",
        default="./slack_auth_state.json",
        help="Path to save/load authentication state"
    )
    
    args = parser.parse_args()
    
    print(f"\n{'='*60}")
    print(f"Slack Analytics Export Trigger")
    print(f"{'='*60}\n")
    
    types_to_export = []
    if args.type == "all":
        types_to_export = ["overview", "channels", "members"]
    else:
        types_to_export = [args.type]
    
    all_results = []
    for export_type in types_to_export:
        if len(types_to_export) > 1:
            print(f"\n--- Processing {export_type.upper()} ---\n")
        
        results = await trigger_export(
            analytics_type=export_type,
            headless=args.headless,
            screenshot_dir=args.screenshot_dir,
            auth_save_path=args.auth_file
        )
        all_results.append(results)
        
        if len(types_to_export) > 1:
            await asyncio.sleep(2)  # Brief pause between exports
    
    # Summary
    print(f"\n{'='*60}")
    print("SUMMARY")
    print(f"{'='*60}")
    
    for result in all_results:
        status = "✓ SUCCESS" if result["success"] else "✗ FAILED"
        print(f"{status}: {result['analytics_type']}")
        if result["button_clicked"]:
            print(f"  Export triggered - check Slack Files for the CSV")
        for error in result["errors"]:
            print(f"  Error: {error}")
    
    print(f"{'='*60}\n")
    
    all_success = all(r["success"] for r in all_results)
    return 0 if all_success else 1


if __name__ == "__main__":
    exit_code = asyncio.run(main())
    exit(exit_code)

